### ISSUE TITLE
[HELP] Help self-hosting cellxgene instance with custom data file

### ISSUE THREAD

**Issue by kishansripada** [chanzuckerberg/cellxgene-documentation#17]
Hi,

I have data hosted online, but I am having trouble following the instructions for self-hosting the cellxgene software on Heroku. 
Any advice?

**Comment by MaximilianLombardo** [comment]
Hey Kishan - we unfortunately are unable to give official guidance on solutions for self-hosting cellxgene due to the wide variety of environments/use cases. You may want to check out the [other self-hosting examples](https://github.com/chanzuckerberg/cellxgene-documentation/tree/main/desktop/self-hosting) that have been crowdsourced by the cellxgene community.

On a side note, please file future reports in the [cellxgene repo](https://github.com/chanzuckerberg/cellxgene), this one is for documentation. When filing additional reports, you may also want to include more details that give more context on the specific problem you are facing.
